name: absensipkl
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:

  fonts:
    - family: Roboto  # Ganti dengan nama keluarga font
      fonts:
        - asset: fonts/Roboto-Bold.ttf
          weight: 600

  
        
  uses-material-design: true
  assets:

    - assets/images/

